apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: events-service-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/teejayade2244/inframonitor-gitops.git
    targetRevision: main
    path: charts/events-service
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: inframonitor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
