apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Values.namespace }}
  annotations:
    azure.workload.identity/client-id: "{{ .Values.env.AZURE_CLIENT_ID }}"
