apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: create-incident-job-trigger-auth
  namespace: {{ .Values.namespace }}
spec:
  podIdentity:
    provider: azure-workload
    identityId: "{{ .Values.env.AZURE_CLIENT_ID }}"